export const GET_SHIRTS_REQUEST = "GET_SHIRTS_REQUEST";
export const GET_SHIRTS_SUCCSESS = "GET_SHIRTS_SUCCSESS";
export const GET_SHIRTS_FAILURE = "GET_SHIRTS_FAILURE";
export const GET_SHIRTS_BY_SEARCH = "GET_SHIRTS_BY_SEARCH";
